#!/bin/sh

if git diff HEAD^ HEAD --name-only | grep -q "src/argsync/pull.py"; then
  sed -i 's/from argsync.gdrive import load_authorized_gdrive/from gdrive import load_authorized_gdrive/g' "src/argsync/pull.py"
fi

if git diff HEAD^ HEAD --name-only | grep -q "src/argsync/push.py"; then
  sed -i 's/from argsync.gdrive import load_authorized_gdrive/from gdrive import load_authorized_gdrive/g' "src/argsync/push.py"
fi

if git diff HEAD^ HEAD --name-only | grep -q "src/argsync/main.py"; then
  sed -i 's/from argsync.pull import pull as pulling/from pull import pull as pulling/g' "src/argsync/main.py"
  sed -i 's/from argsync.push import push as pushing/from push import push as pushing/g' "src/argsync/main.py"
fi